# Generated by Django 4.0.5 on 2022-06-23 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_comment_create_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='dsec',
            new_name='desc',
        ),
    ]
